name: "Compare Coverage Diff"
author: "Dimitar Stoimenov"

inputs:
  generalCoverageTolerance:
    description: "Maximum allowed difference in percentage for the entire project."
    required: true
  singleLineCoverageTolerance:
    description: "Maximum allowed difference in percentage for a single file."
    required: true
  newFileCoverageThreshold:
    description: "Minimum allowed test coverage in percentage for new/renamed files."
    required: true
  ignoredPaths:
    description: "Paths to folders that should be ignored. You can specify multiple paths separated by commas."
    required: false
  excludeFilePatterns:
    description: "Regex patterns to exclude files by name. Separate multiple patterns with commas."
    required: false

outputs:
  hasIssues:
    description: "Whether there are coverage issues (true/false)"
  coverageReport:
    description: "Formatted coverage report for PR comment"

runs:
  using: "node16"
  main: "dist/index.js"
