#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm/node if available (fixes GitHub Desktop PATH issue)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npm run build
